const ROLE_SETTINGS = {
  foods: {
    id: 'idMeal',
    type: 'meals',
    result: 'meals',
    thumb: 'strMealThumb',
    name: 'strMeal',
    translate: 'comida',
    searchIngredient: (search) => `https://www.themealdb.com/api/json/v1/1/filter.php?i=${search}`,
    searchName: (search) => `https://www.themealdb.com/api/json/v1/1/search.php?s=${search}`,
    searchFirstLetter: (search) => `https://www.themealdb.com/api/json/v1/1/search.php?f=${search}`,
    api: (id) => `https://www.themealdb.com/api/json/v1/1/lookup.php?i=${id}`,
    recomendation: 'drinks',
    apiRecomendation: 'https://www.themealdb.com/api/json/v1/1/search.php?s=',
    apiIngredient: 'https://www.themealdb.com/api/json/v1/1/list.php?i=list',
    apiIngredientPhoto: (ingredient) => `https://www.themealdb.com/images/ingredients/${ingredient}-Small.png`,
    ingredientReturn: 'strIngredient',
    getNationalities: 'https://www.themealdb.com/api/json/v1/1/list.php?a=list',
    apiRandom: 'https://www.themealdb.com/api/json/v1/1/random.php',
  },
  drinks: {
    id: 'idDrink',
    type: 'cocktails',
    result: 'drinks',
    thumb: 'strDrinkThumb',
    name: 'strDrink',
    translate: 'bebida',
    searchIngredient: (search) => `https://www.thecocktaildb.com/api/json/v1/1/filter.php?i=${search}`,
    searchName: (search) => `https://www.thecocktaildb.com/api/json/v1/1/search.php?s=${search}`,
    searchFirstLetter: (search) => `https://www.thecocktaildb.com/api/json/v1/1/search.php?f=${search}`,
    api: (id) => `https://www.thecocktaildb.com/api/json/v1/1/lookup.php?i=${id}`,
    recomendation: 'foods',
    apiRecomendation: 'https://www.thecocktaildb.com/api/json/v1/1/search.php?s=',
    apiIngredient: 'https://www.thecocktaildb.com/api/json/v1/1/list.php?i=list',
    apiIngredientPhoto: (ingredient) => `https://www.thecocktaildb.com/images/ingredients/${ingredient}-Small.png`,
    ingredientReturn: 'strIngredient1',
    getNationalities: 'https://www.thecocktaildb.com/api/json/v1/1/list.php?a=list',
    apiRandom: 'https://www.thecocktaildb.com/api/json/v1/1/random.php',
  },
};

export default ROLE_SETTINGS;
